export const PROFILE = {
  name: "Aneesh Krishna",
  email: "aneeshkrishnaparthasarathy@gmail.com",
  location: "New York City",
  university: "Purdue University",
  github: "https://github.com/Aneesh495",
  linkedin: "https://www.linkedin.com/in/aneesh495",
};

export const EXPERIENCES = [
  {
    id: "optiver",
    company: "Optiver",
    role: "HPC Intern",
    period: "Incoming",
    location: "Internship",
    summary: "Incoming HPC intern.",
    bullets: [],
    technologies: [],
  },
  {
    id: "amazon",
    company: "Amazon",
    role: "Engineering",
    period: "2026",
    location: "Internship",
    summary: "Pricing infrastructure and data pipelines on AWS.",
    bullets: [
      "Built services for workbook automation and concurrent job processing.",
      "Added document rewriting and live Redshift enrichment for downstream systems.",
    ],
    technologies: ["AWS", "Redshift", "Python"],
  },
  {
    id: "caterpillar",
    company: "Caterpillar",
    role: "Engineering",
    period: "2025",
    location: "ML / Forecasting",
    summary: "Forecasting models and production inference.",
    bullets: [
      "Designed a multi-horizon transformer for supply-chain forecasting.",
      "Deployed batch inference on Kubernetes and an Azure training-to-serving pipeline.",
    ],
    technologies: ["PyTorch", "Kubernetes", "Azure", "MLOps"],
  },
  {
    id: "handshake",
    company: "Handshake",
    role: "Engineering",
    period: "2025",
    location: "AI / Alignment",
    summary: "RLHF and evaluation for code models.",
    bullets: [
      "Built an RLHF pipeline from preference data through training.",
      "Wrote a sandboxed harness to score generated code off-host.",
    ],
    technologies: ["Python", "RLHF", "LLMs"],
  },
  {
    id: "stealth",
    company: "Stealth Startup",
    role: "Engineering",
    period: "2024",
    location: "Startup",
    summary: "Realtime simulation and engine infrastructure.",
    bullets: [
      "Built game-state synchronization for multiplayer sessions.",
      "Rebuilt the ECS with event-driven updates and object pooling.",
    ],
    technologies: ["ECS", "Networking"],
  },
];

export const PROJECTS = [
  {
    title: "Quasar",
    kind: "Hardware",
    blurb: "Matching engine",
    signal: "SystemVerilog, AXI-Stream, price-time priority",
    bullets: [
      "Price-time priority in silicon. RAM-backed books, indexed cancels, and registered best prices.",
      "AXI-Stream orders through CRC, risk checks, and clock-domain crossings.",
    ],
    technologies: ["SystemVerilog", "AXI", "FPGA"],
    href: "https://github.com/Aneesh495/quasar",
    hrefLabel: "GitHub",
  },
  {
    title: "Cathode",
    kind: "Systems",
    blurb: "CPU graphics engine",
    signal: "Software rendering, handwritten SIMD, analog DSP",
    bullets: [
      "Software rasterization and handwritten AArch64 NEON. Pixels come from the CPU.",
      "Frames pass through an NTSC encode/decode chain, then phosphor decay, bloom, and scanlines.",
    ],
    technologies: ["C", "AArch64 NEON", "Rust", "DSP"],
    href: "https://github.com/Aneesh495/cathode",
    hrefLabel: "GitHub",
  },
  {
    title: "Planck",
    kind: "Systems",
    blurb: "Out-of-order RISC-V core",
    signal: "Cycle-accurate OoO, RV32IM, pure assembly",
    bullets: [
      "An RV32IM assembler, interpreter, and two-wide out-of-order core written in x86-64 assembly.",
      "Register renaming, a reorder buffer, caches, and branch prediction. No C runtime on the host.",
    ],
    technologies: ["x86-64 Assembly", "RISC-V", "Microarchitecture"],
    href: "https://github.com/Aneesh495/planck",
    hrefLabel: "GitHub",
  },
  {
    title: "Crucible",
    kind: "Systems",
    blurb: "Concurrency simulator",
    signal: "Deterministic schedules, fault injection, strict replay",
    bullets: [
      "A seeded runtime for concurrent algorithms and distributed protocols, with bounded schedule exploration.",
      "Injects crashes and partitions, checks histories, and replays the schedule that broke them.",
    ],
    technologies: ["C#", "Distributed Systems", "Linearizability"],
    href: "https://github.com/Aneesh495/Crucible",
    hrefLabel: "GitHub",
  },
  {
    title: "Lockstep",
    kind: "Systems",
    blurb: "Trading exchange",
    signal: "Deterministic matching, WAL, dual-feed market data",
    bullets: [
      "Price-time matching, pre-trade risk, and fixed pools on the hot path.",
      "WAL and snapshots for recovery; dual UDP feeds with sequence-gap detection.",
    ],
    technologies: ["C++20", "UDP", "Exchange"],
    href: "https://github.com/Aneesh495/lockstep",
    hrefLabel: "GitHub",
  },
  {
    title: "VectorTick",
    kind: "Systems",
    blurb: "Market-data engine",
    signal: "Columnar storage, typed SQL, custom JIT",
    bullets: [
      "PCAP ingestion into compressed columnar storage, with typed SQL and vectorized execution.",
      "Handwritten native code generation on x86-64 and AArch64, plus deterministic replay.",
    ],
    technologies: ["C++20", "JIT", "Columnar Storage"],
    href: "https://github.com/Aneesh495/VectorTick",
    hrefLabel: "GitHub",
  },
  {
    title: "Vibe",
    kind: "Systems",
    blurb: "Distributed messenger",
    signal: "Java NIO, binary protocol, WAL and Raft",
    bullets: [
      "A messenger built from the socket up: custom NIO transport, binary framing, and ordered delivery.",
      "Local WAL or replicated Raft durability, bounded backpressure, and offline client outboxes.",
    ],
    technologies: ["Java", "NIO", "Raft", "React"],
    href: "https://github.com/Aneesh495/vibe",
    hrefLabel: "GitHub",
  },
  {
    title: "Glyph",
    kind: "Language",
    blurb: "Functional language toolchain",
    signal: "OCaml, Hindley-Milner inference, SSA, bytecode VM",
    bullets: [
      "A strict functional language with algebraic data types, pattern matching, and Hindley-Milner inference.",
      "Source through SSA and verified bytecode to a register VM with a copying garbage collector.",
    ],
    technologies: ["OCaml", "Compilers", "Type Systems"],
    href: "https://github.com/Aneesh495/glyph",
    hrefLabel: "GitHub",
  },
  {
    title: "Zenith",
    kind: "Language",
    blurb: "WebAssembly runtime",
    signal: "Pure PHP, Wasm interpreter, WASI, terminal debugger",
    bullets: [
      "A WebAssembly interpreter, validator, and WASI runtime written in PHP, without third-party packages.",
      "Compiles WAT, reads Wasm binaries, and lets you step through the stack in a terminal debugger.",
    ],
    technologies: ["PHP", "WebAssembly", "WASI"],
    href: "https://github.com/Aneesh495/zenith",
    hrefLabel: "GitHub",
  },
];
